KeyError: monomorphic.
This is a bit nasty: since exception types must be monomorphic,
  the obvious design for KeyError cannot be used.  [could we cast
  it to any type and use reflection?]

generator code modernized.